backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - 
        label: "Body"
        name: "body"
        widget: "markdown"
        required: true
      - 
        label: "Main Image"
        name: "main_image"
        widget: "image"
        required: false
      - 
        label: "Buttons"
        name: "buttons"
        widget: "list"
        required: false
        fields:
          - { label: "Button Text", name: "button_text", widget: "string", required: true }
          - { label: "Button Link", name: "button_link", widget: "string", required: true }
          - 
            label: "Button Style"
            name: "button_style"
            widget: "select"
            options:
              - "Primary"
              - "Secondary"
            default: "Primary"
      -
        label: "Videos"
        name: "videos"
        widget: "list"
        required: false
        fields:
          - { label: "Video URL", name: "video_url", widget: "string", required: true }
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings/general.yml"
        label: "General Settings"
        name: "general_settings"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Footer Text", name: "footer_text", widget: "text" }

